### ISSUE TITLE
add HN sections

### ISSUE THREAD

**Issue by iamlambda** [rajatkulkarni95/hckrnws#21]
Adding HN sections (i.e past, show, ask) would be convenient to browse the website with ease. To me, it's the last feature that this project lacks before it becomes the best HN front-end.

**Comment by rajatkulkarni95** [comment]
I've been thinking about adding Show for a while, might as well add the rest.

I'll open up a PR in a day or two!

Glad you're liking the app!

**Comment by iamlambda** [comment]
Hey, hope you're doing well.
Just a little bump since it's been more than a month and you still haven't open a PR.

**Comment by rajatkulkarni95** [comment]
Hey! I've been swamped with work and a different project I've been working on so couldn't push it out. I have a working branch for this up, just requires a few design tweaks before I release it. Most likely by the weekend!

**Comment by rajatkulkarni95** [comment]
Added in #27
