### ISSUE TITLE
Add a link to go to parent comment

### ISSUE THREAD

**Issue by Victor239** [rajatkulkarni95/hckrnws#28]
I use a RSS reader to get notifications for responses to my HN comments. When I follow these links to view the comments, I'm unable to click the < arrow to view my parent comment because I navigated directly to the child comment. 

It would be helpful to have a link to view the parent comment under each comment, like HN does.

**Comment by rajatkulkarni95** [comment]
@Victor239 Thanks for taking the time to use the app and open this issue.

I've opened a PR that possibly fixes this, and is rudimentary in design, but I wanted to ask a few questions before I merge it and refine:
1. Could you take a look at the implementation of the PR at this [preview link](https://pretty-news-git-feat-parent-root-comment-link-rajatkulkarni.vercel.app), and if it attempts to solve the use case.
2. Does your RSS reader have the links like `/stories/<story-id>#<comment-id>` , meaning if the url has it, I'd like to find and scroll to that point in the view as well.
3. Does root also make sense?

**Comment by Victor239** [comment]
1. No it doesn't unfortunately. Take a look [at this](https://pretty-news-git-feat-parent-root-comment-link-rajatkulkarni.vercel.app/stories/31293038) child comment for example.
2. HN uses the same URL structure for individual comments as it does for normal posts it appears like e.g. https://news.ycombinator.com/item?id=31293038
3. Root also makes sense, though on HN it's named "context".

**Comment by rajatkulkarni95** [comment]
Oh! So you want the `back` icon to take you to the parent comment? Not the `parent`, `root` that the comments you are viewing currently, but rather the ones you have been transported to

**Comment by rajatkulkarni95** [comment]
Well not necessarily the `back` icon, but another icon that loads the `parent comment` url

**Comment by rajatkulkarni95** [comment]
@Victor239 Unfortunately it seems to be a limitation of the API currently, since there is no available context to the individual comment currently,

```
comments: Array []
comments_count: 0
content: "<p>Unless the NSA, FBI, or whoever comes out and says oh we broke Tor, I don&#x27;t see how you could ever get a definite answer to that question. And I don&#x27;t really see that happening.<p>Or it could leaked, on accident or by a whistleblower. But that&#x27;s pretty uncommon."
id: 31293038
time: 1651912776
time_ago: "5 hours ago"
type: "comment"
url: "item?id=31293038"
user: "uluyol"
```

As you see the individual comment has no relative parent, or even the post that it is a child to in the API. Would need to experiment a bit with the [official hackernews api](https://github.com/HackerNews/API) since the one used in this app [HNPWA](https://github.com/tastejs/hacker-news-pwas/blob/master/docs/api.md) seems to not be capable of handling this

**Comment by Victor239** [comment]
Ah that's unfortunate. Hope this can be figured out.

**Comment by hacker-DOM** [comment]
Hey, thanks for the project
Unfortunately this is a dealbreaker for me :(
