### ISSUE TITLE
Apostrophes are not rendered (`&#x27;` is `'`)

### ISSUE THREAD

**Issue by aklsh** [rajatkulkarni95/hckrnws#32]
![image](https://user-images.githubusercontent.com/45280368/203970481-b6ba8435-e00e-4a48-9852-0cef7273bca3.png)

I'm not familiar with JS/TS or webdev really so can't really create a PR to fix this.

**Comment by rajatkulkarni95** [comment]
Nice find, can you post the link so its easy to reproduce and fix?

**Comment by aklsh** [comment]
https://www.hckrnws.com/stories/33739583

**Comment by rajatkulkarni95** [comment]
@aklsh Should work as expected now! Thanks for giving the app a try

**Comment by aklsh** [comment]
Oh nice! [hckrnws.com](hckrnws.com) is what [news.ycombinator.com](news.ycombinator.com) should look like - dark mode + open links in new tab. Thanks a lot for making this.
