### ISSUE TITLE
do you have an instances list

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [rajatkulkarni95/hckrnws#34]

**Comment by rajatkulkarni95** [comment]
Unsure what you mean by instances list

**Comment by EsmailELBoBDev2** [comment]
I self-host hckrnws so asking if can I add my instance somewhere in wiki or readme.md

**Comment by rajatkulkarni95** [comment]
Got it. Currently no plans to add an instances file for alternatives unfortunately. Glad the self host works for you though
