### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by ganeshlab** [rajatkulkarni95/hckrnws#38]
Ran into this issue while trying to use the docker version, then tried building from source and got these errors. I was able to build [myshen's](https://github.com/myshen/hckrnws) older fork.

> Error occurred prerendering page "/ask/2". Read more: https://nextjs.org/docs/messages/prerender-error
SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6498:19)
    at successSteps (node:internal/deps/undici/undici:6472:27)
    at node:internal/deps/undici/undici:1145:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

>  Build error occurred
Error: Export encountered errors on following paths:
	/ask/[number]: /ask/2
    at /opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/export/index.js:425:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:79:20)
    at async /opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:1403:21
    at async Span.traceAsyncFn (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:79:20)
    at async /opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:1261:17
    at async Span.traceAsyncFn (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:72:29)

**Comment by kuanhulio** [comment]
Having the same issue as well.

**Comment by kuanhulio** [comment]
```
#19 0.707
#19 0.707 > hckrnws@ build /opt/app
#19 0.707 > next build
#19 0.707
#19 1.106 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#19 1.106 This information is used to shape Next.js' roadmap and prioritize features.
#19 1.106 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#19 1.106 https://nextjs.org/telemetry
#19 1.106
#19 1.215 info  - Linting and checking validity of types...
#19 3.443 info  - Creating an optimized production build...
#19 7.406
#19 7.406 warn - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`.
#19 7.406 warn - Update your configuration file to silence this warning.
#19 7.406
#19 7.406 warn - As of Tailwind CSS v3.0, `warmGray` has been renamed to `stone`.
#19 7.406 warn - Update your configuration file to silence this warning.
#19 7.406
#19 7.406 warn - As of Tailwind CSS v3.0, `trueGray` has been renamed to `neutral`.
#19 7.407 warn - Update your configuration file to silence this warning.
#19 7.407
#19 7.407 warn - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.
#19 7.407 warn - Update your configuration file to silence this warning.
#19 7.407
#19 7.407 warn - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
#19 7.407 warn - Update your configuration file to silence this warning.
#19 7.489
#19 7.489 warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
#19 7.489 warn - Change `darkMode` to `media` or remove it entirely.
#19 7.489 warn - https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
#19 9.732 info  - Compiled successfully
#19 9.740 info  - Collecting page data...
#19 10.32 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 10.33 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 10.33 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 10.34 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 10.35 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 10.36 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 13.73 info  - Generating static pages (0/27)
#19 13.93 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 13.94 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 13.95 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 14.24 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 14.24 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 14.25 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 14.26 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 14.26 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 14.34 [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
#19 14.43 info  - Generating static pages (6/27)
#19 14.57 info  - Generating static pages (13/27)
#19 14.57
#19 14.57 Error occurred prerendering page "/ask/2". Read more: https://nextjs.org/docs/messages/prerender-error
#19 14.57 SyntaxError: Unexpected token C in JSON at position 0
#19 14.57     at JSON.parse (<anonymous>)
#19 14.57     at parseJSONFromBytes (node:internal/deps/undici/undici:6498:19)
#19 14.57     at successSteps (node:internal/deps/undici/undici:6472:27)
#19 14.57     at node:internal/deps/undici/undici:1145:60
#19 14.57     at node:internal/process/task_queues:140:7
#19 14.57     at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
#19 14.57     at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
#19 14.57     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#19 14.62 info  - Generating static pages (20/27)
#19 14.71 info  - Generating static pages (27/27)
#19 14.71
#19 14.71 > Build error occurred
#19 14.71 Error: Export encountered errors on following paths:
#19 14.71       /ask/[number]: /ask/2
#19 14.71     at /opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/export/index.js:425:19
#19 14.71     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#19 14.71     at async Span.traceAsyncFn (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:79:20)
#19 14.71     at async /opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:1403:21
#19 14.71     at async Span.traceAsyncFn (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:79:20)
#19 14.71     at async /opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:1261:17
#19 14.71     at async Span.traceAsyncFn (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:79:20)
#19 14.71     at async Object.build [as default] (/opt/app/node_modules/.pnpm/next@13.2.3_@babel+core@7.21.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/index.js:72:29)
#19 14.74  ELIFECYCLE  Command failed with exit code 1.
------
```

**Comment by rajatkulkarni95** [comment]
Do you need to do a 'next export'?

**Comment by rajatkulkarni95** [comment]
The older fork used getServerSideProps, but the latest use getStatic so the pages are built, during build with ISR.

Unsure how this is supported in the docker version (since I have bare minimum knowledge about Docker) 

Ref - https://nextjs.org/docs/advanced-features/static-html-export

**Comment by kuanhulio** [comment]
> The older fork used getServerSideProps, but the latest use getStatic so the pages are built, during build with ISR.
> 
> Unsure how this is supported in the docker version (since I have bare minimum knowledge about Docker)
> 
> Ref - https://nextjs.org/docs/advanced-features/static-html-export

This would be done via your `next.config.js`

**Comment by kuanhulio** [comment]
Unless I'm mistaken, this would require editing of the `next.config.js` and the `package.json` build command for this to work through.

**Comment by ganeshlab** [comment]
Sorry for mentioning docker, I don't believe it to be relevant here. I was able to complete the build process by removing /src/pages/ask/ so the issue seems to be isolated to something in there. Wish I could be of more help.

**Comment by rajatkulkarni95** [comment]
I'll take a look when I'm back home, but essentially you are saying that

```
pnpm install 
pnpm build
```

Is failing for you.

**Comment by ganeshlab** [comment]
That's right.

**Comment by rajatkulkarni95** [comment]
@ganeshlab  @kuanhulio Alright so was able to get to the root of it, and it isn't an issue on the code, but rather the API. So for some reason `https://api.hnpwa.com/v0/ask/2.json` API returns an error (you can click the link to give it a try, `https://api.hnpwa.com/v0/ask/1.json` the first page loads fine though)

So when we are building the pages when doing `pnpm run build` this error from the API is causing the actual build to fail. Unsure if there's a fix for it now, since https://hckrnws.com seems to be working fine for now.


Sorry I don't have any other solution but you can do one thing to make it build locally.

Go over to your forks https://github.com/rajatkulkarni95/hckrnws/blob/main/src/pages/ask/%5Bnumber%5D.tsx#L68 this line, and change

```
  const paths = [...Array(2)].map((x, idx) => ({
    params: { number: (idx + 1).toString() },
  }));
```
to

```
  const paths = [...Array(1)].map((x, idx) => ({
    params: { number: (idx + 1).toString() },
  }));
  ```
  
  so that it doesn't attempt to build the second page.

**Comment by ganeshlab** [comment]
I think they must've fixed it on their end. The link to 2.json works and pnpm build finishes without errors. Thanks for looking into it.

**Comment by kuanhulio** [comment]
Just want to make sure I'm correct @rajatkulkarni95, building the service can fail if the API fails for some reason?

**Comment by rajatkulkarni95** [comment]
Yes @kuanhulio due to we building all the pages at build time. A downside of getStaticProps but also better in a way so that api failures don't make to prod
