### ISSUE TITLE
add link to comment

### ISSUE THREAD

**Issue by iamlambda** [rajatkulkarni95/hckrnws#39]
It would be nice to be able to link to a comment, which will show the comment and its thread. Just like you can do with ycombinator when clicking `x hours ago` on a comment or the share button on reddit.

**Comment by rajatkulkarni95** [comment]
https://user-images.githubusercontent.com/57321156/229855240-84b6c364-f965-42dd-a449-36bec1151587.mov

**Comment by iamlambda** [comment]
great this is exactly what I was thinking about. Though I'm not sure about having to hover the area to be able to see the icon, since for keyboard driven browsing it clearly isn't optimal, even tho it looks really clean that way.

**Comment by rajatkulkarni95** [comment]
Merged. Will remove the hover in the next PR if it's too inaccessible after using it for a day or two

**Comment by rajatkulkarni95** [comment]
Thanks for using it and providing feedback! Appreciate it
