### ISSUE TITLE
Hckrnws.com Domain Lost?

### ISSUE THREAD

**Issue by whispy** [rajatkulkarni95/hckrnws#45]
Is the domain lost? Was it not renewed?

**Comment by rajatkulkarni95** [comment]
> Is the domain lost? Was it not renewed?

Yeah. Had it on auto renew. Vercel messed up even after changing cards.

Opened a ticket up, got back to me after it was already expired. 

Have no way of redirecting people, but updated the github about with the new link!

**Comment by rajatkulkarni95** [comment]
Working with them currently to see if it's still in the grace period and if manual renewal would work
