### ISSUE TITLE
Bug: Copying comment url copies invalid url

### ISSUE THREAD

**Issue by ginruh** [rajatkulkarni95/hckrnws#46]
In any story for example https://www.hckrnws.com/stories/39079256, if one tries to copy any comment url we get `VERCEL_URL/stories/<comment_id>`.

I think you can fix this from environment variables exposed via vercel panel if you are using vercel. If not then I think specifying the required variable in `next.config.js` will fix this bug.

**Comment by rajatkulkarni95** [comment]
Had to fix the variable in the vercel panel. Now works fine!

https://github.com/rajatkulkarni95/hckrnws/assets/57321156/c3246861-7826-45cb-b8c5-8a1d2f65dafc

Thanks for the report
